# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('expire_data', models.DateField()),
                ('issue_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Book')),
                ('issue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Student')),
            ],
        ),
    ]
