# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='expire_data',
            new_name='expire_date',
        ),
    ]
