# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('It', 'IT Department'), ('Computer', 'Computer Department'), ('Bba', ' BBA Department'), ('Electronic', 'Electronic and Communication Department'), ('Civil', 'Civil Department')], default='It', max_length=30),
        ),
    ]
