# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_auto_20180228_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='book_detail',
        ),
        migrations.AddField(
            model_name='book',
            name='category_title',
            field=models.CharField(choices=[('It', 'IT Department'), ('Computer', 'Computer Department'), ('Bba', ' BBA Department'), ('Electronic', 'Electronic and Communication Department'), ('Civil', 'Civil Department')], default='It', max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
