# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_auto_20180301_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category_title',
            field=models.CharField(max_length=30),
        ),
    ]
