# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_auto_20180304_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='expire_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.DateTimeField(),
        ),
    ]
