# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0012_auto_20180308_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='expire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.DateField(),
        ),
    ]
